### PR TITLE
Unfoldable.generate

### PR DESCRIPTION
**Pull request by matthewleon**
Construct an Unfoldable by applying a function to an incremented index.

### CODE REVIEW

**Comment by paf31** [comment]
Isn't this the same as `map f [0..]` in Haskell. Maybe the simplest thing would be to just export `nats :: Unfoldable f => f Int`

**Comment by matthewleon** [comment]
This PR avoids creating an ephemeral data structure to map over. I imagine that GHC is smart enough to stop that from happening, but we will be `unfold`ing strict data structures in PureScript (and the lazy lists we do have retain a reference to the head).

That said, exporting `nats` seems like a reasonable idea as well.

**Comment by paf31** [comment]
I think there are a lot of cases where we could do map fusion on behalf of the compiler, in libraries, but I don't think we should. If someone needs fusion to happen enough, they can write the definition inline in a `where` clause, right? The core libraries shouldn't do _everything_, just enough, in my opinion at least.

**Comment by matthewleon** [comment]
Sounds reasonable. I'll get around to a PR for `nats` soon then.

**Comment by matthewleon** [comment]
Now that I reconsider, though, the issue with exporting `nats` is that it only works on lazy structures. I guess that's the issue for me... Either we do fusion ourselves, or the function won't terminate.

Am I overlooking a simple solution?

**Comment by paf31** [comment]
In that case, I think what we need is a `range` function.

**Pull request closed without merging**
