### PR TITLE
iterateN

### PR DESCRIPTION
**Pull request by matthewleon**
Create an `Unfoldable` by repeated application of a function to a seed value.

### CODE REVIEW

**Review by JordanMartinez — DISMISSED** [review]

**Comment by JordanMartinez** [comment]
Hm... CI is failing because `Unfoldable1`, which already defines its version of `singleton` and `range`, is also exported from the `Unfoldable` module. So, it exports two members with the same name twice.

Merging this would require a breaking change.

**Comment by JordanMartinez** [comment]
Since `Unfoldable1` is a super class of `Unfoldable`, all types that implement `Unfoldable` (e.g. Array) also implement `Unfoldable1`. However, the reverse (e.g. `NonEmptyArray`) is not the case.

`iterateN` can be redefined to use `Unfoldable1` and get the same behavior. See this gist: https://try.purescript.org/?gist=8b4cd9f94df2189ea0ec15c55309911e

**Comment by JordanMartinez** [comment]
This also explains why `singleton` and `range` are re-exported from `Data.Unfoldable1` and do not have a separate definition using `Unfoldable`.

**Comment by JordanMartinez** [comment]
:ping_pong: @thomashoneyman

**Comment by thomashoneyman** [comment]
Is there a reason or precedent for the `*N` suffix, as opposed to just naming this `iterate`?

**Comment by JordanMartinez** [comment]
I think `iterateN` is similar to Haskell. Consider:
- `iterate`: https://hoogle.haskell.org/?hoogle=iterate&scope=set%3Astackage
- `iterateN`: https://hoogle.haskell.org/?hoogle=iterateN&scope=set%3Astackage

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
