### PR TITLE
Use an FFI implementation for Array unfold

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by garyb** [comment]
This is necessary so that we can provide `toUnfoldable` in `purescript-arrays`: the implementation I'm replacing dependend on `arrays` for `STArray`, leaving us with a dependency graph issue.

The implementation is based on the original, pre-ST implementation but using PS functions rather than assuming anything about how `Maybe`, `Tuple`, etc. are represented in JS.

/cc @sharkdp

**Comment by paf31** [comment]
:+1: Looks good, if maybe a little bit inefficient. How does it perform compared to the old version?

**Comment by paf31** [comment]
Perhaps it's possible to get rid of the `unsafePartial` call by providing a single fold function for `Maybe (Tuple _ _)` of type `forall r. r -> (a -> b -> r) -> r`.

**Comment by garyb** [comment]
`unsafePartial` is being called "statically" (at definition time) here so there's no overhead if that's what you're thinking about?

Performance is... decent. Using this highly sophisticated benchmark:

``` purescript
intz :: Int -> Array Int
intz = U.unfoldr step
  where
  step 1 = Nothing
  step n = Just (Tuple n (n - 1))

main :: Eff (console :: CONSOLE) Unit
main = do
  logShow $ Data.Array.length $ intz 1000000
  logShow $ Data.Array.length $ intz 1000000
  logShow $ Data.Array.length $ intz 1000000
  logShow $ Data.Array.length $ intz 1000000
  logShow $ Data.Array.length $ intz 1000000
```

Original:

```
real	0m16.083s
user	0m16.313s
sys	0m0.395s
```

After switching to FFI:

```
real	0m1.118s
user	0m1.437s
sys	0m0.287s
```

:wink:

**Comment by paf31** [comment]
Looks good then! Thanks :ship:

**Pull request merged**
